### PR TITLE
Added bear image

### LINKED ISSUE #1: Testing features of github for integration

### PR DESCRIPTION
**Pull request by darshana-threado**

### CODE REVIEW

**Comment by DarshanaSahu** [comment]
Checking for comments in the PR

**Comment by DarshanaSahu** [comment]
Added deer image to check PR commits

**Review by DarshanaSahu — APPROVED** [review]
PR changes look good

**Review by djgupta — CHANGES_REQUESTED** [review]
add one more image

**Comment by DarshanaSahu** [comment]
test PR comment api through postman

**Comment by DarshanaSahu** [comment]
test posting PR comment through UI

**Comment by DarshanaSahu** [comment]
test final

**Comment by DarshanaSahu** [comment]
trying it once again

**Comment by DarshanaSahu** [comment]
check pull request webhook event

**Comment by darshana-threado** [comment]
1. test PR comment api through postman

**Comment by darshana-threado** [comment]
1. test PR comment api through postman

**Comment by darshana-threado** [comment]
1\. test pr throught UI # @ & 1 . / \* \\ once again he he

**Comment by darshana-threado** [comment]
1\.

**Comment by darshana-threado** [comment]
1\.

**Comment by darshana-threado** [comment]
1\. \

**Comment by DarshanaTest** [comment]
" "

**Comment by DarshanaSahu** [comment]
Again.

Through UI.

OK.

**Pull request merged**
